export const site = {
  name: "Tracemail",
  tagline: "Email forensics, evidence first.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://g-doc-three.vercel.app",
  description:
    "Free AI email threat detector. Upload a suspicious .eml file to check for phishing, spam, junk and scam emails, verify SPF, DKIM and DMARC, trace sender IP geolocation and scan links with VirusTotal.",
  keywords: [
    "email threat detection",
    "phishing email checker",
    "phishing detector",
    "spam email checker",
    "junk mail detector",
    "email junk detector",
    "scam email checker",
    "fake email detector",
    "is this email safe",
    "suspicious email analyzer",
    "email header analyzer",
    "eml file analyzer",
    "email forensics",
    "email security tool",
    "SPF DKIM DMARC checker",
    "email sender IP lookup",
    "email IP geolocation",
    "malicious link checker",
    "malicious attachment scanner",
    "business email compromise detection",
    "CEO fraud email",
    "AI email security",
    "email spoofing detection",
  ],
  authors: [
    { name: "Bhuvanesh J" },
    { name: "D Prem Sankar", url: "https://prem.ikaruz.in", role: "UI/UX Design" },
  ],
};
